maxGameLength: 500 # Max game length (in seconds), bot will try to quit game arrived that point

# Required to avoid the 30 days not logged issue, since the game requires internet connection even to play offline
username: '' # Battle.net username
password: '' # Battle.net pwd
realm: 'eu.actual.battle.net' # Battle.net realm (kr.actual.battle.net, us.actual.battle.net, eu.actual.battle.net)
authMethod: 'None' # Authentication method the bot will use (None, BattleNetClient, UsernamePassword)
characterName: '' # If left empty, koolo will use first listed character, if name is wrong, it will fail to create the game
commandLineArgs: '' # Command line arguments for D2
killD2OnStop: true # Terminate D2 process on bot stop
classicMode: false # Set to true to use legacy graphics
closeMiniPanel: false # Set to true to close the mini panel at start of game in legacy graphics
hidePortraits: true  # Set to true to hide mercenary and other players portraits (avatar)
enableCubeRecipes: true # Enable cubing of flawlesses and tokens

scheduler:
  enabled: false
  days:
    - dayOfWeek: 0
      timeRange: []
    - dayOfWeek: 1
      timeRange: []
    - dayOfWeek: 2
      timeRange: []
    - dayOfWeek: 3
      timeRange: []
    - dayOfWeek: 4
      timeRange: []
    - dayOfWeek: 5
      timeRange: []
    - dayOfWeek: 6
      timeRange: []

health: # Healing configuration, all values in %
  healingPotionAt: 75
  manaPotionAt: 10
  rejuvPotionAtLife: 50
  rejuvPotionAtMana: 0
  mercHealingPotionAt: 80
  mercRejuvPotionAt: 30
  chickenAt: 30
  mercChickenAt: 10

inventory:
  inventoryLock:
    - [ 1, 1, 1, 1, 1, 1, 1, 0, 0, 0 ] # 0: Item locked and won't be moved.
    - [ 1, 1, 1, 1, 1, 1, 1, 0, 0, 0 ] # 1: Item unlocked, it will be stashed, sold or dropped.
    - [ 1, 1, 1, 1, 1, 1, 1, 0, 0, 0 ]
    - [ 1, 1, 1, 1, 1, 1, 1, 0, 0, 0 ]

  beltColumns: [healing, healing, mana, rejuvenation] # 4 values, each represents the belt column type, allowed values: healing, mana, rejuvenation

character:
  class: sorceress # Allowed values: sorceress, lightning, hammerdin, foh, paladin (leveling only)
  useMerc: true
  stashToShared: false
  useTeleport: true # If set to false, bot will not use teleport skill and will walk to the destination

game:
  minGoldPickupThreshold: 500000 # If total gold amount is less than this, bot will pick up and sell magic+ items
  clearTPArea: true # Will clear the TP area before clicking it
  difficulty: hell # Allowed values: normal, nightmare, hell
  randomizeRuns: true # Will randomize the order of the runs each game
  # Just add the runs you want to do and they will be executed respecting the order, unless randomizeRuns is set to true
  # Available runs: countess, andariel, ancient_tunnels, summoner, mephisto, council, eldritch, pindleskin, nihlathak,
  #                 tristram, lower_kurast, lower_kurast_chest, stony_tomb, pit, arachnid_lair, tal_rasha_tombs, baal, diablo, cows, terror_zone
  # leveling: there is a "leveling" run, in combination with "sorceress or paladin" class will be able to start leveling character from level 1 (don't expect too much)
  # terror_zone: will detect current TZ and clear it
  runs: [ stony_tomb, pit, arachnid_lair ]

  # Specific runs settings
  pindleskin:
    skipOnImmunities: [ ] # Allowed values: cold, fire, light, poison
  stony_tomb:
    openChests: true
    focusOnElitePacks: false
  ancient_tunnels:
    openChests: true
    focusOnElitePacks: false
  drifter_cavern:
    openChests: true
    focusOnElitePacks: false
  spider_cavern:
    openChests: true
    focusOnElitePacks: false
  pit:
    # default - Outer Cloister -> Monastery Gates -> Tamoe Highland
    moveThroughBlackMarsh: false # Use Black Marsh -> Tamoe Highland route
    openChests: true
    focusOnElitePacks: false
    onlyClearLevel2: false
  mephisto:
    killCouncilMembers: true # Will kill the council members after killing Mephisto
    openChests: true # Will open chests after killing Mephisto
  tristram:
    focusOnElitePacks: false # Will clear only Elite monsters
    clearPortal: true # Kills Rakanishu and makes easier selecting the portal
  nihlathak:
    clearArea: true
  diablo:
    killDiablo: true # Should bot kill Diablo after seals
    clearArea: true # Should bot clear Chaos Sanctuary
    onlyElites: true # Should bot target only elites
  baal:
    killBaal: false
    dollQuit: false
    soulQuit: false
  eldritch:
    killShenk: true
  leveling:
    ensurePointsAllocation: true # Bot will allocate skill and stat points by itself or perform stat/skill reset. Set to false if you do NOT want it
    ensureKeyBinding: true       # Bot will set key bindings by itself. Set to false if you want to do it manually
  terror_zone:
    focusOnElitePacks: false # Will clear only Elite monsters
    skipOnImmunities: [ ] # Allowed values: cold, fire, light, poison
    skipOtherRuns: false # If current TZ is allowed, will skip other runs and only do TZ instead
    areas:
      - 2 # Blood Moor
      - 8 # Den of Evil
      - 3 # Cold Plains
      - 9 # Cave Level 1
      - 10 # Cave Level 2
      - 12 # Pit Level 1 (Will do Pit run)
      - 17 # Burial Grounds
      - 18 # Crypt
      - 19 # Mausoleum
      - 4 # Stony Field
      - 5 # Dark Wood
      - 10 # Underground Passage Level 1
      - 14 # Underground Passage Level 2
      - 6 # Black Marsh
      - 11 # Hole Level 1
      - 15 # Hole Level 2
      - 20 # Forgotten Tower (Will do Countess run)
      - 29 # Jail Level 1
      - 30 # Jail Level 2
      - 31 # Jail Level 3
      - 32 # Inner Cloister
      - 33 # Cathedral
      - 34 # Catacombs Level 1
      - 35 # Catacombs Level 2
      - 36 # Catacombs Level 3
      - 38 # Tristram (Will do Tristram run)
      - 39 # Moo Moo Farm (Will do Cows run)
      - 41 # Rocky Waste (Will do Stony Tomb run)
      - 47 # Sewers Level 1
      - 48 # Sewers Level 2
      - 49 # Sewers Level 3
      - 42 # Dry Hills
      - 56 # Halls of the Dead Level 1
      - 57 # Halls of the Dead Level 2
      - 60 # Halls of the Dead Level 3
      - 43 # Far Oasis
      - 44 # Lost City
      - 45 # Valley of Snakes
      - 58 # Claw Viper Temple Level 1
      - 61 # Claw Viper Temple Level 2
      - 65 # Ancient Tunnels (Will do Ancient Tunnels run)
      - 66 # Tal Rasha's Tomb 1 (Will do Tal Rasha Tombs run)
      - 74 # Arcane Sanctuary (Will do Summoner run)
      - 76 # Spider Forest
      - 85 # Spider Cavern
      - 83 # Travincal (Will do Council run)
      - 77 # Great Marsh
      - 78 # Flayer Jungle
      - 88 # Flayer Dungeon Level 1
      - 89 # Flayer Dungeon Level 2
      - 91 # Flayer Dungeon Level 3
      - 80 # Kurast Bazaar
      - 94 # Ruined Temple
      - 95 # Disused Fane
      - 100 # Durance of Hate Level 1 (Will do Mephisto run)
      - 104 # Outer Steppes
      - 105 # Plains of Despair
      - 106 # City of the Damned
      - 107 # River of Flame
      - 108 # Chaos Sanctuary (Will do Diablo run)
      - 110 # Bloody Foothills
      - 111 # Frigid Highlands
      - 125 # Abaddon
      - 115 # Glacial Trail
      - 116 # Drifter Cavern
      - 113 # Crystalline Passage
      - 114 # Frozen River
      - 112 # Arreat Plateau
      - 126 # Pit of Acheron
      - 118 # The Ancients' Way
      - 119 # Icy Cellar
      - 121 # Nihlathak's Temple (Will do Nihlathak run)
      - 128 # The Worldstone Keep Level 1 (Will do Baal run)
  countess:
    clearGhosts: false # Will go room to room in the Tower and kill every ghost.   

companion:
  enabled: false
  leader: true
  leaderName: ''
  attack: true # If set to true, character will try to attack the same target as the leader
  followLeader: true # If set to true, character will follow the leader, otherwise will stay in the same area
  gameNameTemplate: game- # Template for the game name, for example "game-" will lead to "game-1", "game-2", etc.
  gamePassword: xxx

# Gambling settings. If enabled, bot will start gambling when all the gold stash tabs are full.
# While gold > 500k it will iterate over the items list trying to buy one of each item type.
# Item filtering will be done via the same pickup configuration, discarded items will be sold to vendor
gambling:
  enabled: true # If gambling is disabled, bot will stop picking up gold when can not carry more
  items: [ coronet, amulet, ring ] # Items to gamble, same value as [name] in pickit files.

backtotown:
  noHpPotions: true
  noMpPotions: false
  mercDied: true
