display: 0
debug: true
logFilePath: log.txt
maxGameLength: 300 # Max game length (in seconds), bot will try to quit game arrived that point

health: # Healing configuration, all values in %
  healingPotionAt: 85
  manaPotionAt: 10
  rejuvPotionAtLife: 40
  rejuvPotionAtMana: 0
  mercHealingPotionAt: 80
  mercRejuvPotionAt: 20
  chickenAt: 20
  mercChickenAt: 0

bindings:
  potion1: 1
  potion2: 2
  potion3: 3
  potion4: 4

  # Skills
  forceMove: h
  standStill: j
  swapWeapon: g
  teleport: q
  tp: t
  CTABattleCommand: s
  CTABattleOrders: d

  # Class specific bindings
  sorceress:
    blizzard: w
    staticField: e
    frozenArmor: a

inventory:
  inventoryLock:
    - [1, 1, 1, 1, 1, 1, 1, 1, 0, 0] # 0: Item locked and won't be moved.
    - [1, 1, 1, 1, 1, 1, 1, 1, 0, 0] # 1: Item unlocked, it will be stashed, sold or dropped.
    - [1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
    - [1, 1, 1, 1, 1, 1, 1, 1, 0, 0]

  beltColumns: # Amount of columns for each type of potion, sum of all should not be more than 4
    healing: 2
    mana: 1
    rejuvenation: 1
  beltRows: 4
  
character:
  class: Sorceress # Allowed values: Sorceress
  castingFrames: 9 # https://diablo2.diablowiki.net/Breakpoints#Faster_Cast_Rate
  difficulty: hell # Allowed values: normal, nightmare, hell
  useMerc: true
  useCTA: true

runs:
  countess: false
  andariel: true
  summoner: true
  mephisto: true
  council: true
  pindleskin: true
  nihlathak: false

